
// workplace advice array with 20 advices
const workplace_advice = [
    "Use tools like to-do lists and calendars to manage your tasks efficiently.",
    "Ensure your messages can be understood by all parties by being clear and consise.",
    "Arrive on time for meetings and appointments to show respect.",
    "Set goals and objectives to guide your work and measure progress.",
    "Actively listen and pay attention to what others say to improve collaboration.",
    "Maintain a positive attitude even in challenging situations.",
    "Learn from your mistakes and use them as opportunities to grow and improve.",
    "Always be open to changes and new ideas in your workplace.",
    "Express your gratitude to colleagues for their help and support.",
    "Taking regular breaks can boost productivity and reduce stress.",
    "Drink plenty of water throughout the day to stay focused.",
    "Share appropriate jokes to lighten the mood and reduce tension.",
    "Treat colleagues with kindness and respect.",
    "Prioritize the most important tasks first to maximize efficiency.",
    "Don't hesitate to ask for feedback to improve your performance and skills.",
    "Be Proactive: Anticipate challenges and take initiative to solve them.",
    "Leverage tools and technologies to streamline work processes and save time.",
    "Celebrate successes and achievements to boost morale!",
    "Maintain a healthy balance between your work life and personal life.",
    "Continuously seek knowledge and skills to enhance your professional growth."];

const financial_advice = [
    "Create a detailed budget to track income and expenses.",
    "Set specific and realistic financial goals for short- and long-term planning.",
    "Build an emergency fund covering 3-6 months of living expenses.",
    "Pay off high-interest debt, such as credit card balances, as fast as possible.",
    "Contribute to retirement accounts, especially if your employer offers matching.",
    "Automate savings transfers to enforce consistent saving habits.",
    "Keep your savings in a high-yield savings account for better returns.",
    "Calculate and monitor your net worth regularly.",
    "Use the 50/30/20 budget rule: 50% for needs, 30% for wants, and 20% for savings and debt repayment.",
    "Take advantage of employer benefits, such as 401(k) matching and health insurance perks.",
    "Consider refinancing or consolidating debt to lower interest rates.",
    "Invest in a diversified portfolio to spread risk and potentially increase returns.",
    "Create a financial calendar to track important money-related dates and tasks.",
    "Pay bills on time to avoid late fees and maintain a good credit score.",
    "Regularly review and adjust your insurance coverage to ensure adequate protection.",
    "Educate yourself on personal finance topics to make informed decisions.",
    "Use cash for discretionary spending to better control your expenses.",
    "Avoid lifestyle inflation as your income increases.",
    "Consider opening an Individual Retirement Account (IRA) for additional tax-advantaged savings.",
    "Review your financial plan regularly and adjust as needed to stay on track."
];
